Création des composants UserCard et UserProCard
Catif/LP-PTUT_Scudo pull request #31
Opened 2023-02-10 15:50 UTC by Catif

Créations des deux composants utilisées pour afficher les statistiques et un bouton "suivre" sur les profils des utilisateurs (Pro ou non)

# Version mobile : 
### Utilisateur : 
![image](https://user-images.githubusercontent.com/84462178/218134490-e2f76250-6471-4ca1-9377-1a711c3b7b63.png)

### Utilisateur Pro : 
![image](https://user-images.githubusercontent.com/84462178/218134820-5624a8bc-f2ea-40ce-a03c-7918fe03c783.png)

# Version Desktop : 
### Utilisateur : 
![image](https://user-images.githubusercontent.com/84462178/218134579-3bc4f93e-bcf1-4451-b2c6-707b62e931bd.png)

### Utilisateur Pro : 
![image](https://user-images.githubusercontent.com/84462178/218134907-32bd4893-16eb-45fa-b2b8-55b780d3abff.png)

2023-02-10 16:01 UTC, Catif commented
Ajout d'un store pour la gestion de fonctions futures.
Utilisation de la fonction formatNumber() crée dans ce nouveau store pour générer les nombres de façon formater, exemple 2000 => 2k  ; 2354 => 2.36k
![image](https://user-images.githubusercontent.com/84462178/218137821-a7d73200-a7b6-45d5-878b-b1234149931f.png)

2023-02-10 17:04 UTC, lecyp12 requested changes

2023-02-10 17:04 UTC, lecyp12 submitted a review, later dismissed

2023-02-11 11:04 UTC, lecyp12 approved these changes

2023-02-13 09:51 UTC, JUEChristopher approved these changes

2023-02-13 13:05 UTC, merged