Fake data generation class and script
Catif/LP-PTUT_Scudo pull request #60
Opened 2023-02-17 16:25 UTC by JUEChristopher

2023-02-17 16:32 UTC, Catif approved these changes

2023-02-18 21:38 UTC, Catif requested changes

2023-02-18 21:38 UTC, Catif commented on api/public/index.php
> +for($u = 0; $u < 25; $u++){
Mettre en commentaire cette partie, ou mieux faire un fichier à part pour déporter le code autre part, comme ça on a juste besoin de mettre en commentaire le require qui lance le script

2023-02-19 11:20 UTC, uzanzi submitted a review, later dismissed

2023-02-19 15:19 UTC, JUEChristopher commented on api/public/index.php
> +for($u = 0; $u < 25; $u++){
Le script se trouve désormais dans sql/ et est appelé dans l'index. De plus la base de données qui était dans conf/ n'était pas la dernière version de celle-ci (pas d'uuid sur toutes les tables, etc). J'ai donc mis la dernière version et une nouvelle génération de la demo, avec un paramètre dans le script SQL pour la timezone, seulement celui-ci ne change rien puisqu'il semblerais que Eloquent force la création des timestamps en UTC +00:00. Malgré le paramètre db_timezone dans conf/db.ini en +01:00.

2023-02-19 16:36 UTC, Catif submitted a review, later dismissed

2023-02-20 18:14 UTC, uzanzi submitted a review, later dismissed

2023-04-10 11:11 UTC, merged